#ifndef RESOURCE_H
#define RESOURCE_H

#ifdef FONTLOADERSUB_MESON_BUILD
#include "fontloadersub_version.h"
#endif

#ifndef FONTLOADERSUB_GIT_VERSION
#define FONTLOADERSUB_GIT_VERSION "2.0.0"
#endif

#define IDS_APP_NAME_VER 2
#define IDS_SHELL_VERB 4
#define IDS_SENDTO 6
#define IDS_LOAD_STAT 8
#define IDS_WORK_CANCELLING 10
#define IDS_WORK_SUBTITLE 12
#define IDS_WORK_CACHE 14
#define IDS_WORK_FONT 16
#define IDS_WORK_LOAD 18
#define IDS_WORK_UNLOAD 20
#define IDS_WORK_DONE 22
#define IDS_HELP 24
#define IDS_USAGE 26
#define IDS_MANAGE_SHORTCUT 28
#define IDS_SHORTCUT_ERROR_ADD 30
#define IDS_SHORTCUT_ERROR_DEL 32
#define IDS_SHORTCUT_ADD_DIR_BG 34
#define IDS_SHORTCUT_DEL_DIR_BG 36
#define IDS_SHORTCUT_ADD_SENDTO 38
#define IDS_SHORTCUT_DEL_SENDTO 40
#define IDS_MENU 42
#define IDS_WORK_CHECK 44
#define IDS_MISSING_FONT 46
#define IDS_MISSING_FONT_CONTENT 48
#define IDS_CONTINUE_LOAD 50
#define IDS_MISSING_EXPAND 52
#define IDS_MISSING_COLLAPSE 54
#define IDS_DUPLICATE_FONT 56
#define IDS_DUPLICATE_FONT_CONTENT 58
#define IDS_DUPLICATE_FONT_NONE 60
#define IDS_DUPLICATE_EXPAND 62
#define IDS_DUPLICATE_COLLAPSE 64
#define IDS_DUPLICATE_IDENTICAL 66
#define IDS_DUPLICATE_VERSIONS 68
#define IDS_DUPLICATE_UNKNOWN_VERSION 70
#define IDS_CLOSE 72

// control id
#define ID_BTN_MENU 101
#define ID_BTN_RESCAN 102
#define ID_BTN_EXPORT 103
#define ID_BTN_HELP 104
#define ID_BTN_CONTINUE_LOAD 105
#define ID_BTN_DUPLICATE_FONT 106
#define IDC_DUPLICATE_SUMMARY 107
#define IDC_DUPLICATE_LIST 108

// menu
#define IDR_BTN_MENU 1
#define IDD_DUPLICATE_FONT 2

#endif
