// automatically generated by the FlatBuffers compiler, do not modify
// schema: font_db.fbs

#ifndef FONTLOADER_FONT_DB_GENERATED_H_
#define FONTLOADER_FONT_DB_GENERATED_H_

#include <cstdint>

#ifndef NOMINMAX
#define NOMINMAX
#endif

#include <flatbuffers/flatbuffers.h>

namespace fontloader {

enum FontFormat : uint8_t {
  FontFormat_None = 0,
  FontFormat_OTF = 1,
  FontFormat_TTF = 2,
  FontFormat_TTC = 3,
  FontFormat_MIN = FontFormat_None,
  FontFormat_MAX = FontFormat_TTC
};

inline const char *EnumNameFontFormat(FontFormat e) {
  switch (e) {
  case FontFormat_None:
    return "None";
  case FontFormat_OTF:
    return "OTF";
  case FontFormat_TTF:
    return "TTF";
  case FontFormat_TTC:
    return "TTC";
  default:
    return "";
  }
}

struct FontEntry FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_TAG = 4,
    VT_FACE = 6,
    VT_VER = 8,
    VT_FORMAT = 10
  };
  const flatbuffers::String *tag() const {
    return GetPointer<const flatbuffers::String *>(VT_TAG);
  }
  const flatbuffers::String *face() const {
    return GetPointer<const flatbuffers::String *>(VT_FACE);
  }
  const flatbuffers::String *ver() const {
    return GetPointer<const flatbuffers::String *>(VT_VER);
  }
  FontFormat format() const {
    return static_cast<FontFormat>(GetField<uint8_t>(VT_FORMAT, 0));
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TAG) &&
           verifier.VerifyString(tag()) &&
           VerifyOffset(verifier, VT_FACE) &&
           verifier.VerifyString(face()) &&
           VerifyOffset(verifier, VT_VER) &&
           verifier.VerifyString(ver()) &&
           verifier.EndTable();
  }
};

struct FontEntryBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit FontEntryBuilder(flatbuffers::FlatBufferBuilder &fbb)
      : fbb_(fbb) {
    start_ = fbb_.StartTable();
  }
  void add_tag(flatbuffers::Offset<flatbuffers::String> tag) {
    fbb_.AddOffset(FontEntry::VT_TAG, tag);
  }
  void add_face(flatbuffers::Offset<flatbuffers::String> face) {
    fbb_.AddOffset(FontEntry::VT_FACE, face);
  }
  void add_ver(flatbuffers::Offset<flatbuffers::String> ver) {
    fbb_.AddOffset(FontEntry::VT_VER, ver);
  }
  void add_format(FontFormat format) {
    fbb_.AddElement<uint8_t>(FontEntry::VT_FORMAT, static_cast<uint8_t>(format), 0);
  }
  flatbuffers::Offset<FontEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    return flatbuffers::Offset<FontEntry>(end);
  }
};

inline flatbuffers::Offset<FontEntry> CreateFontEntry(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flatbuffers::String> tag = 0,
    flatbuffers::Offset<flatbuffers::String> face = 0,
    flatbuffers::Offset<flatbuffers::String> ver = 0,
    FontFormat format = FontFormat_None) {
  FontEntryBuilder builder(fbb);
  builder.add_ver(ver);
  builder.add_face(face);
  builder.add_tag(tag);
  builder.add_format(format);
  return builder.Finish();
}

struct FontDb FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_VERSION = 4,
    VT_NUM_FILE = 6,
    VT_NUM_FACE = 8,
    VT_ENTRIES = 10
  };
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 1);
  }
  uint32_t num_file() const {
    return GetField<uint32_t>(VT_NUM_FILE, 0);
  }
  uint32_t num_face() const {
    return GetField<uint32_t>(VT_NUM_FACE, 0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<FontEntry>> *entries() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<FontEntry>> *>(VT_ENTRIES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyField<uint32_t>(verifier, VT_NUM_FILE, 4) &&
           VerifyField<uint32_t>(verifier, VT_NUM_FACE, 4) &&
           VerifyOffset(verifier, VT_ENTRIES) &&
           verifier.VerifyVector(entries()) &&
           verifier.VerifyVectorOfTables(entries()) &&
           verifier.EndTable();
  }
};

struct FontDbBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit FontDbBuilder(flatbuffers::FlatBufferBuilder &fbb)
      : fbb_(fbb) {
    start_ = fbb_.StartTable();
  }
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(FontDb::VT_VERSION, version, 1);
  }
  void add_num_file(uint32_t num_file) {
    fbb_.AddElement<uint32_t>(FontDb::VT_NUM_FILE, num_file, 0);
  }
  void add_num_face(uint32_t num_face) {
    fbb_.AddElement<uint32_t>(FontDb::VT_NUM_FACE, num_face, 0);
  }
  void add_entries(
      flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<FontEntry>>> entries) {
    fbb_.AddOffset(FontDb::VT_ENTRIES, entries);
  }
  flatbuffers::Offset<FontDb> Finish() {
    const auto end = fbb_.EndTable(start_);
    return flatbuffers::Offset<FontDb>(end);
  }
};

inline flatbuffers::Offset<FontDb> CreateFontDb(
    flatbuffers::FlatBufferBuilder &fbb,
    uint32_t version = 1,
    uint32_t num_file = 0,
    uint32_t num_face = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<FontEntry>>> entries = 0) {
  FontDbBuilder builder(fbb);
  builder.add_entries(entries);
  builder.add_num_face(num_face);
  builder.add_num_file(num_file);
  builder.add_version(version);
  return builder.Finish();
}

inline const FontDb *GetFontDb(const void *buf) {
  return flatbuffers::GetRoot<FontDb>(buf);
}

inline const FontDb *GetSizePrefixedFontDb(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<FontDb>(buf);
}

inline bool VerifyFontDbBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<FontDb>("FTDB");
}

inline bool VerifySizePrefixedFontDbBuffer(flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<FontDb>("FTDB");
}

inline const char *FontDbIdentifier() {
  return "FTDB";
}

}  // namespace fontloader

#endif  // FONTLOADER_FONT_DB_GENERATED_H_
