// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FONTDB_FONTLOADER_H_
#define FLATBUFFERS_GENERATED_FONTDB_FONTLOADER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace fontloader {

struct FontEntry;
struct FontEntryBuilder;

struct FontDb;
struct FontDbBuilder;

enum FontFormat : int8_t {
  FontFormat_None = 0,
  FontFormat_OTF = 1,
  FontFormat_TTF = 2,
  FontFormat_TTC = 3,
  FontFormat_MIN = FontFormat_None,
  FontFormat_MAX = FontFormat_TTC
};

inline const FontFormat (&EnumValuesFontFormat())[4] {
  static const FontFormat values[] = {
    FontFormat_None,
    FontFormat_OTF,
    FontFormat_TTF,
    FontFormat_TTC
  };
  return values;
}

inline const char * const *EnumNamesFontFormat() {
  static const char * const names[5] = {
    "None",
    "OTF",
    "TTF",
    "TTC",
    nullptr
  };
  return names;
}

inline const char *EnumNameFontFormat(FontFormat e) {
  if (::flatbuffers::IsOutRange(e, FontFormat_None, FontFormat_TTC)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesFontFormat()[index];
}

struct FontEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FontEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TAG = 4,
    VT_FACE = 6,
    VT_VER = 8,
    VT_FORMAT = 10,
    VT_HASH_LOW64 = 12,
    VT_HASH_HIGH64 = 14
  };
  const ::flatbuffers::String *tag() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TAG);
  }
  const ::flatbuffers::String *face() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FACE);
  }
  const ::flatbuffers::String *ver() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VER);
  }
  fontloader::FontFormat format() const {
    return static_cast<fontloader::FontFormat>(GetField<int8_t>(VT_FORMAT, 0));
  }
  uint64_t hash_low64() const {
    return GetField<uint64_t>(VT_HASH_LOW64, 0);
  }
  uint64_t hash_high64() const {
    return GetField<uint64_t>(VT_HASH_HIGH64, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TAG) &&
           verifier.VerifyString(tag()) &&
           VerifyOffset(verifier, VT_FACE) &&
           verifier.VerifyString(face()) &&
           VerifyOffset(verifier, VT_VER) &&
           verifier.VerifyString(ver()) &&
           VerifyField<int8_t>(verifier, VT_FORMAT, 1) &&
           VerifyField<uint64_t>(verifier, VT_HASH_LOW64, 8) &&
           VerifyField<uint64_t>(verifier, VT_HASH_HIGH64, 8) &&
           verifier.EndTable();
  }
};

struct FontEntryBuilder {
  typedef FontEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tag(::flatbuffers::Offset<::flatbuffers::String> tag) {
    fbb_.AddOffset(FontEntry::VT_TAG, tag);
  }
  void add_face(::flatbuffers::Offset<::flatbuffers::String> face) {
    fbb_.AddOffset(FontEntry::VT_FACE, face);
  }
  void add_ver(::flatbuffers::Offset<::flatbuffers::String> ver) {
    fbb_.AddOffset(FontEntry::VT_VER, ver);
  }
  void add_format(fontloader::FontFormat format) {
    fbb_.AddElement<int8_t>(FontEntry::VT_FORMAT, static_cast<int8_t>(format), 0);
  }
  void add_hash_low64(uint64_t hash_low64) {
    fbb_.AddElement<uint64_t>(FontEntry::VT_HASH_LOW64, hash_low64, 0);
  }
  void add_hash_high64(uint64_t hash_high64) {
    fbb_.AddElement<uint64_t>(FontEntry::VT_HASH_HIGH64, hash_high64, 0);
  }
  explicit FontEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FontEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FontEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FontEntry> CreateFontEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> tag = 0,
    ::flatbuffers::Offset<::flatbuffers::String> face = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ver = 0,
    fontloader::FontFormat format = fontloader::FontFormat_None,
    uint64_t hash_low64 = 0,
    uint64_t hash_high64 = 0) {
  FontEntryBuilder builder_(_fbb);
  builder_.add_hash_high64(hash_high64);
  builder_.add_hash_low64(hash_low64);
  builder_.add_ver(ver);
  builder_.add_face(face);
  builder_.add_tag(tag);
  builder_.add_format(format);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FontEntry> CreateFontEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *tag = nullptr,
    const char *face = nullptr,
    const char *ver = nullptr,
    fontloader::FontFormat format = fontloader::FontFormat_None,
    uint64_t hash_low64 = 0,
    uint64_t hash_high64 = 0) {
  auto tag__ = tag ? _fbb.CreateString(tag) : 0;
  auto face__ = face ? _fbb.CreateString(face) : 0;
  auto ver__ = ver ? _fbb.CreateString(ver) : 0;
  return fontloader::CreateFontEntry(
      _fbb,
      tag__,
      face__,
      ver__,
      format,
      hash_low64,
      hash_high64);
}

struct FontDb FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FontDbBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_NUM_FILE = 6,
    VT_NUM_FACE = 8,
    VT_ENTRIES = 10
  };
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 1);
  }
  uint32_t num_file() const {
    return GetField<uint32_t>(VT_NUM_FILE, 0);
  }
  uint32_t num_face() const {
    return GetField<uint32_t>(VT_NUM_FACE, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fontloader::FontEntry>> *entries() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fontloader::FontEntry>> *>(VT_ENTRIES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyField<uint32_t>(verifier, VT_NUM_FILE, 4) &&
           VerifyField<uint32_t>(verifier, VT_NUM_FACE, 4) &&
           VerifyOffset(verifier, VT_ENTRIES) &&
           verifier.VerifyVector(entries()) &&
           verifier.VerifyVectorOfTables(entries()) &&
           verifier.EndTable();
  }
};

struct FontDbBuilder {
  typedef FontDb Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(FontDb::VT_VERSION, version, 1);
  }
  void add_num_file(uint32_t num_file) {
    fbb_.AddElement<uint32_t>(FontDb::VT_NUM_FILE, num_file, 0);
  }
  void add_num_face(uint32_t num_face) {
    fbb_.AddElement<uint32_t>(FontDb::VT_NUM_FACE, num_face, 0);
  }
  void add_entries(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fontloader::FontEntry>>> entries) {
    fbb_.AddOffset(FontDb::VT_ENTRIES, entries);
  }
  explicit FontDbBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FontDb> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FontDb>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FontDb> CreateFontDb(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 1,
    uint32_t num_file = 0,
    uint32_t num_face = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fontloader::FontEntry>>> entries = 0) {
  FontDbBuilder builder_(_fbb);
  builder_.add_entries(entries);
  builder_.add_num_face(num_face);
  builder_.add_num_file(num_file);
  builder_.add_version(version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FontDb> CreateFontDbDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 1,
    uint32_t num_file = 0,
    uint32_t num_face = 0,
    const std::vector<::flatbuffers::Offset<fontloader::FontEntry>> *entries = nullptr) {
  auto entries__ = entries ? _fbb.CreateVector<::flatbuffers::Offset<fontloader::FontEntry>>(*entries) : 0;
  return fontloader::CreateFontDb(
      _fbb,
      version,
      num_file,
      num_face,
      entries__);
}

inline const fontloader::FontDb *GetFontDb(const void *buf) {
  return ::flatbuffers::GetRoot<fontloader::FontDb>(buf);
}

inline const fontloader::FontDb *GetSizePrefixedFontDb(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fontloader::FontDb>(buf);
}

inline const char *FontDbIdentifier() {
  return "FTDB";
}

inline bool FontDbBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, FontDbIdentifier());
}

inline bool SizePrefixedFontDbBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, FontDbIdentifier(), true);
}

inline bool VerifyFontDbBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fontloader::FontDb>(FontDbIdentifier());
}

inline bool VerifySizePrefixedFontDbBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fontloader::FontDb>(FontDbIdentifier());
}

inline void FinishFontDbBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fontloader::FontDb> root) {
  fbb.Finish(root, FontDbIdentifier());
}

inline void FinishSizePrefixedFontDbBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fontloader::FontDb> root) {
  fbb.FinishSizePrefixed(root, FontDbIdentifier());
}

}  // namespace fontloader

#endif  // FLATBUFFERS_GENERATED_FONTDB_FONTLOADER_H_
